version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: php-sql-db-container
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin
      MYSQL_DATABASE: php-sql-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
